In [6]:
import numpy as np
import csv

In [211]:
import pandas as pd
data = pd.read_csv('IPL.csv')
data.head()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9968\1672211075.py:2: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('IPL.csv')

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
#first group year wise batsman and calculate runs for each batter in each year
#then sort them reverse and print the 3rd highest run scorer

In [23]:
data['year'] = data['date'].dt.year
data['year'].value_counts().sort_index()

year
2008    13489
2009    13606
2010    14498
2011    17013
2012    17767
2013    18177
2014    14300
2015    13652
2016    14096
2017    13862
2018    14286
2019    14312
2020    14559
2021    14425
2022    17912
2023    17863
2024    17103
2025    17285
Name: count, dtype: int64

In [32]:
yearly_runs = data.groupby(['year','batter'])['runs_batter'].sum().reset_index()

In [37]:
yearly_runs = yearly_runs.sort_values(['year','runs_batter'],ascending=[True,False])

In [38]:
highest = yearly_runs.groupby('year').nth(2).reset_index()

In [39]:
print(highest)

    index  year          batter  runs_batter
0     126  2008   ST Jayasuriya          514
1     165  2009  AB de Villiers          465
2     441  2010        SK Raina          528
3     623  2011    SR Tendulkar          553
4     785  2012        S Dhawan          569
5     983  2013         V Kohli          639
6    1025  2014      GJ Maxwell          552
7    1183  2015     LMP Simmons          540
8    1256  2016  AB de Villiers          687
9    1495  2017        S Dhawan          479
10   1592  2018        KL Rahul          659
11   1764  2019       Q de Kock          529
12   1833  2020       DA Warner          548
13   2007  2021        KL Rahul          626
14   2207  2022       Q de Kock          508
15   2311  2023       DP Conway          672
16   2550  2024         R Parag          573
17   2772  2025         V Kohli          657

In [43]:
yearly_wicket = data.groupby(['year','bowler'])['bowler_wicket'].sum().reset_index()
yearly_wicket = yearly_wicket.sort_values(['year','bowler_wicket'],ascending=[True,False])
third_purple = yearly_wicket.groupby('year').nth(2).reset_index()
third_purple

    index  year           bowler  bowler_wicket
0      77  2008         SK Warne             19
1     102  2009          A Nehra             19
2     211  2010         A Mishra             17
3     432  2011        S Aravind             21
4     575  2012       SL Malinga             22
5     640  2013  Harbhajan Singh             24
6     734  2014          B Kumar             20
7     924  2015        YS Chahal             23
8    1018  2016        SR Watson             20
9    1076  2017        JJ Bumrah             20
10   1217  2018           S Kaul             21
11   1257  2019        DL Chahar             22
12   1430  2020         TA Boult             25
13   1478  2021        JJ Bumrah             21
14   1592  2022         K Rabada             23
15   1782  2023      Rashid Khan             27
16   1848  2024        JJ Bumrah             20
17   1988  2025     JR Hazlewood             22

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  datetime64[ns]
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int32
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), int64(23), object(34)
memory usage: 129.2+ MB

In [90]:
#Display the first 10 rows of the dataset.

data.head(10)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
5,131975,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,...,2,5,0,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False
6,131976,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,...,3,6,0,NaN,0,5,0,"('BB McCullum', 'SC Ganguly')",NaN,False
7,131977,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,...,3,7,0,NaN,0,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False
8,131978,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,...,7,8,0,NaN,4,7,0,"('BB McCullum', 'SC Ganguly')",NaN,False
9,131979,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,...,11,9,0,NaN,8,8,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [92]:
# Display the last 5 rows of the dataset.

data.tail(5)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
278200,277951,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,2,...,162,116,7,NaN,39,26,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278201,277952,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,3,...,168,117,7,NaN,45,27,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278202,277953,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,4,...,172,118,7,NaN,49,28,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278203,277954,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,5,...,178,119,7,NaN,55,29,0,"('KA Jamieson', 'Shashank Singh')",NaN,False
278204,277955,1473511,2025-06-03,T20,Indian Premier League,2,Punjab Kings,Royal Challengers Bengaluru,19,6,...,184,120,7,NaN,61,30,0,"('KA Jamieson', 'Shashank Singh')",NaN,False

In [93]:
# Display the shape of the dataset.

data.shape

(278205, 64)

In [94]:
# Display the column names of the dataset.

data.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out'],
      dtype='object')

In [95]:
# Display information about the dataset.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  datetime64[ns]
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int32
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), int64(23), object(34)
memory usage: 129.2+ MB

In [51]:
# Display information about perticular column.

data['gender'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 278205 entries, 0 to 278204
Series name: gender
Non-Null Count   Dtype
--------------   -----
278205 non-null  object
dtypes: object(1)
memory usage: 2.1+ MB

In [96]:
# Count the total number of matches played

match_id = np.array(data['match_id'].values)
unique_match_id = np.unique(match_id)
print(len(unique_match_id))

1169

In [86]:
# Check if there are any missing values in the dataset.

missing_values = data.isnull().sum()
total_missing_values = sum(missing_values)
total_missing_values

3670259

In [87]:
# Count missing values column-wise.

missing_values = missing_values[missing_values > 0]
print(missing_values.sort_values(ascending=False))

review_batter       277333
team_reviewed       277333
review_decision     277333
umpire              277333
method              274315
superover_winner    274309
result_type         273503
fielders            268192
new_batter          264884
next_batter         264884
wicket_kind         264382
player_out          264382
extra_type          263072
runs_target         144302
win_outcome           4702
dtype: int64

In [103]:
# Find the number of unique seasons in the dataset

data['season'] = data['season'].astype(str)
seasons = np.array(data['season'].values)
unique_seasons = np.unique(seasons)
print(len(unique_seasons))

18

In [266]:
# Find how many matches were played in each season.

data['season'] = data['season'].astype(str)
data['season'] = data['season'].str.split('/').str[0]
print(data.groupby('season')['match_id'].nunique().reset_index())

   season  match_id
0    2007        58
1    2009       117
2    2011        73
3    2012        74
4    2013        76
5    2014        60
6    2015        59
7    2016        60
8    2017        59
9    2018        60
10   2019        60
11   2020        60
12   2021        60
13   2022        74
14   2023        74
15   2024        71
16   2025        74

In [149]:
#Find the total number of matches won by each team.

matches_won_per_team = data.groupby('match_won_by')['match_id'].nunique().sort_values(ascending=False)
print(matches_won_per_team)

match_won_by
Mumbai Indians                 151
Chennai Super Kings            142
Kolkata Knight Riders          135
Rajasthan Royals               114
Royal Challengers Bangalore    114
Sunrisers Hyderabad             93
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  51
Gujarat Titans                  37
Punjab Kings                    34
Lucknow Super Giants            30
Deccan Chargers                 29
Unknown                         23
Royal Challengers Bengaluru     18
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: match_id, dtype: int64

In [151]:
#Find the top 5 teams with the most wins.

print(matches_won_per_team[0:5])

match_won_by
Mumbai Indians                 151
Chennai Super Kings            142
Kolkata Knight Riders          135
Rajasthan Royals               114
Royal Challengers Bangalore    114
Name: match_id, dtype: int64

In [152]:
#Find the number of matches played at each venue.

matches_per_venue = data.groupby('venue')['match_id'].nunique().sort_values(ascending=False)
print(matches_per_venue)

venue
Eden Gardens                                                               77
Wankhede Stadium                                                           73
M Chinnaswamy Stadium                                                      65
Feroz Shah Kotla                                                           60
Wankhede Stadium, Mumbai                                                   52
Rajiv Gandhi International Stadium, Uppal                                  49
MA Chidambaram Stadium, Chepauk                                            48
Sawai Mansingh Stadium                                                     47
Dubai International Cricket Stadium                                        46
Punjab Cricket Association Stadium, Mohali                                 35
MA Chidambaram Stadium, Chepauk, Chennai                                   34
Narendra Modi Stadium, Ahmedabad                                           33
Sheikh Zayed Stadium                                                       29
Sharjah Cricket Stadium                                                    28
Eden Gardens, Kolkata                                                      23
Arun Jaitley Stadium, Delhi                                                23
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow      22
Maharashtra Cricket Association Stadium                                    22
Dr DY Patil Sports Academy, Mumbai                                         20
Rajiv Gandhi International Stadium, Uppal, Hyderabad                       19
M Chinnaswamy Stadium, Bengaluru                                           19
Sawai Mansingh Stadium, Jaipur                                             17
Brabourne Stadium, Mumbai                                                  17
Dr DY Patil Sports Academy                                                 17
Subrata Roy Sahara Stadium                                                 16
Kingsmead                                                                  15
Rajiv Gandhi International Stadium                                         15
M.Chinnaswamy Stadium                                                      15
Arun Jaitley Stadium                                                       14
Maharashtra Cricket Association Stadium, Pune                              13
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                        13
Sardar Patel Stadium, Motera                                               12
SuperSport Park                                                            12
Punjab Cricket Association IS Bindra Stadium, Mohali                       11
Saurashtra Cricket Association Stadium                                     10
Punjab Cricket Association IS Bindra Stadium                               10
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur         10
Brabourne Stadium                                                          10
MA Chidambaram Stadium                                                      9
Holkar Cricket Stadium                                                      9
Himachal Pradesh Cricket Association Stadium                                9
Zayed Cricket Stadium, Abu Dhabi                                            8
New Wanderers Stadium                                                       8
St George's Park                                                            7
Barabati Stadium                                                            7
JSCA International Stadium Complex                                          7
Newlands                                                                    7
Himachal Pradesh Cricket Association Stadium, Dharamsala                    6
Shaheed Veer Narayan Singh International Stadium                            6
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh            5
Nehru Stadium                                                               5
Barsapara Cricket Stadium, Guwahati                                         5
Green Park                                                                  4
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam          4
Buffalo Park                                                                3
De Beers Diamond Oval                                                       3
Vidarbha Cricket Association Stadium, Jamtha                                3
OUTsurance Oval                                                             2
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh     1
Name: match_id, dtype: int64

In [169]:
# Find venues where matches are played frequently.

matches = (
    data.groupby('match_id')
        .agg({
            'date': 'first',
            'venue': 'first'
        })
        .reset_index()
)

matches['date'] = pd.to_datetime(matches['date'])
matches = matches.sort_values('date')

matches['prev_date'] = matches['date'].shift()
matches['prev_venue'] = matches['venue'].shift()
matches['date_diff'] = (matches['date'] - matches['prev_date']).dt.days

filtered = matches[
    (matches['venue'] == matches['prev_venue']) &
    (matches['date_diff'] <= 7)
]

result = (
    filtered['venue']
    .value_counts()
    .reset_index(name='count')
)

result.head()

                                 venue  count
0  Dubai International Cricket Stadium     10
1                 Sheikh Zayed Stadium      6
2                            Kingsmead      6
3                      SuperSport Park      6
4             Wankhede Stadium, Mumbai      6

In [181]:
#Find the count of matches where the toss winner also won the match.

matches_won = (
    data.groupby('match_id')
        .agg({
            'toss_winner': 'first',
            'match_won_by': 'first'
        })
        .reset_index()
)

count = (matches_won['toss_winner'] == matches_won['match_won_by']).sum()

print(count)

591

In [216]:
# Filter all matches played in a specific season (choose any season).

data['season'] = data['season'].astype(str)

season_data = data[data['season'] == '2021']

data_2007 = (
    season_data.groupby('match_id')
    .agg({
        'date': 'first',
        'venue': 'first',
        'city': 'first',
        'toss_winner': 'first',
        'toss_decision': 'first',
        'match_won_by': 'first',
        'win_outcome': 'first'
    })
    .reset_index()
)

print(data_2007.head())

   match_id        date                                     venue     city  \
0   1254058  2021-04-09  MA Chidambaram Stadium, Chepauk, Chennai  Chennai
1   1254059  2021-04-10                  Wankhede Stadium, Mumbai   Mumbai
2   1254060  2021-04-11  MA Chidambaram Stadium, Chepauk, Chennai  Chennai
3   1254061  2021-04-12                  Wankhede Stadium, Mumbai   Mumbai
4   1254062  2021-04-13  MA Chidambaram Stadium, Chepauk, Chennai  Chennai

                   toss_winner toss_decision                 match_won_by  \
0  Royal Challengers Bangalore         field  Royal Challengers Bangalore
1               Delhi Capitals         field               Delhi Capitals
2          Sunrisers Hyderabad         field        Kolkata Knight Riders
3             Rajasthan Royals         field                 Punjab Kings
4        Kolkata Knight Riders         field               Mumbai Indians

  win_outcome
0   2 wickets
1   7 wickets
2     10 runs
3      4 runs
4     10 runs

In [219]:
#Filter matches where a specific team won (choose any team).

team_data = data[data['match_won_by'] == 'Chennai Super Kings']

data_csk = (
    team_data.groupby('match_id')
    .agg({
        'date': 'first',
        'venue': 'first',
        'city': 'first',
        'toss_winner': 'first',
        'toss_decision': 'first',
        'match_won_by': 'first',
        'win_outcome': 'first'
    })
    .reset_index()
)

print(data_csk.head())

   match_id        date                                       venue  \
0    335983  2008-04-19  Punjab Cricket Association Stadium, Mohali
1    335989  2008-04-23             MA Chidambaram Stadium, Chepauk
2    335993  2008-04-26             MA Chidambaram Stadium, Chepauk
3    335996  2008-04-28                       M Chinnaswamy Stadium
4    336009  2008-05-08                            Feroz Shah Kotla

         city            toss_winner toss_decision         match_won_by  \
0  Chandigarh    Chennai Super Kings           bat  Chennai Super Kings
1     Chennai         Mumbai Indians         field  Chennai Super Kings
2     Chennai  Kolkata Knight Riders           bat  Chennai Super Kings
3   Bangalore    Chennai Super Kings           bat  Chennai Super Kings
4       Delhi    Chennai Super Kings         field  Chennai Super Kings

  win_outcome
0     33 runs
1      6 runs
2   9 wickets
3     13 runs
4   4 wickets

In [222]:
#Find how many matches were decided by runs vs wickets.

data['win_outcome_type'] = data['win_outcome'].str.split(' ').str[1]
print(data['win_outcome_type'].value_counts())

win_outcome_type
wickets    143832
runs       129671
Name: count, dtype: int64

In [240]:
#Find all matches where the toss decision was "bat".

bat_data = data[data['toss_decision'] == 'bat']

a = bat_data.groupby('match_id').agg({'toss_winner': 'first', 'match_won_by': 'first'}).reset_index()
b = a[a['toss_winner'] == a['match_won_by']]
print(a.head())
print(a.shape)
print(b.shape)

   match_id          toss_winner                 match_won_by
0    335983  Chennai Super Kings          Chennai Super Kings
1    335984     Rajasthan Royals             Delhi Daredevils
2    335985       Mumbai Indians  Royal Challengers Bangalore
3    335986      Deccan Chargers        Kolkata Knight Riders
4    335987      Kings XI Punjab             Rajasthan Royals
(405, 3)
(183, 3)

In [262]:
#Find the average win margin (runs)

matches = (
    data.groupby('match_id')
        .agg({
            'win_outcome': 'first'
        })
        .reset_index()
)

run_wins = matches[
    matches['win_outcome'].str.contains('runs', na=False)
].copy()

run_wins['run_margin'] = pd.to_numeric(
    run_wins['win_outcome'].str.extract(r'(\d+)')[0],
    errors='coerce'
)
print(run_wins['run_margin'].mean())

30.295668549905837

In [268]:
import pandas as pd

df = pd.read_csv("IPL.csv", low_memory=False)

match_df = df.groupby("match_id").agg({
    "season": "first",
    "venue": "first",
    "match_won_by": "first",
    "win_outcome": "first",
    "toss_winner": "first",
    "toss_decision": "first",
    "result_type": "first"
}).reset_index()

In [269]:
match_df["season"].value_counts().sort_index()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
2025       74
Name: count, dtype: int64

In [270]:
match_df["match_won_by"].value_counts()

match_won_by
Mumbai Indians                 151
Chennai Super Kings            142
Kolkata Knight Riders          135
Royal Challengers Bangalore    114
Rajasthan Royals               114
Sunrisers Hyderabad             93
Kings XI Punjab                 85
Delhi Daredevils                67
Delhi Capitals                  51
Gujarat Titans                  37
Punjab Kings                    34
Lucknow Super Giants            30
Deccan Chargers                 29
Unknown                         23
Royal Challengers Bengaluru     18
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [272]:
decided_by_runs = match_df["win_outcome"].str.contains("run", na=False).sum()
decided_by_wickets = match_df["win_outcome"].str.contains("wicket", na=False).sum()
print("Decided by runs:", decided_by_runs)
print("Decided by wickets:", decided_by_wickets)

Decided by runs: 531
Decided by wickets: 615

In [275]:
print(match_df["win_outcome"]\
    .str.extract(r'(\d+) runs')\
    .astype(float)\
    .max())

print(match_df["win_outcome"]\
    .str.extract(r'(\d+) wickets')\
    .astype(float)\
    .max())

0    146.0
dtype: float64
0    10.0
dtype: float64